name: sample
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2 # データベース
  path: ^1.9.0 # ファイルパス
  provider: ^6.1.2 # 状態管理
  intl: ^0.17.0 # 日付フォーマット


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/